### ISSUE TITLE
New Ranks

### ISSUE THREAD

**Issue by Gr1dl0k** [D3monkat/PursuitXErrors#11]
['1'] = { name = 'Officer', payment = 75 },
            ['2'] = { name = 'officer 2', payment = 100 },
            ['3'] = { name = 'Corporal', payment = 125 },
            ['4'] = { name = 'Sergeant', isboss = true, payment = 150 },
            ['5'] = { name = 'Detective', payment = 50 },
            ['6'] = { name = 'Lead Detective', payment = 75 },
            ['7'] = { name = 'Lieutenant', payment = 100 },
            ['8'] = { name = 'Captain', payment = 125 },
            ['9'] = { name = 'Commander', isboss = true, payment = 150 },
            ['10'] = { name = 'Deputy Chief', payment = 50 },
            ['11'] = { name = 'Assistant Chief', payment = 75 },
            ['12'] = { name = 'Chief Of Police', payment = 100 },

**Comment by Gr1dl0k** [comment]
please try to get these done soon thank you

**Comment by Goose206** [comment]
what job is this for

**Comment by Gr1dl0k** [comment]
LSPD

**Comment by Gr1dl0k** [comment]
sorry forgot to mention that

**Comment by Gr1dl0k** [comment]
also if you can make sure the only one assigned as chief of police is raiden kingcade

**Comment by Goose206** [comment]
done. will be fixed after tsunami
