### ISSUE TITLE
LMC

### ISSUE THREAD

**Issue by lilrasclesgaming** [D3monkat/PursuitXErrors#13]
possiable to get LMC GARAGE FOR MULES AND VANS 

LOCKS and stash for materials and guns type deal

BOSSMENU IN THE OFFICE IF POSSIABLE 

CHAIRS FOR CHURCH THAT ARE SITTABLE

**Comment by Jucid** [comment]
gang menu might be possible, but idk about a personal gang garage, locks i could do if ok by kat also once i get perms
