### ISSUE TITLE
Burgershot 

### ISSUE THREAD

**Issue by epicural** [D3monkat/PursuitXErrors#23]
Re-add Burgershot to mapping so I can access it and start selling food their please and thank you

**Comment by NeonDestinyNetwork** [comment]
I'm not sure if mapping was converted for this or not. I'd convert it but I'd have to watch you convert it to learn it

**Comment by epicural** [comment]
okay do I need to have the mlo or script?

**Comment by NeonDestinyNetwork** [comment]
No I was talking about Kat sorry

**Comment by NeonDestinyNetwork** [comment]
For the no pixel stuff conversion

**Comment by epicural** [comment]
no worries
